version: "3.7"

services:
  api:
    container_name: forestApi
    image: api:1.0.0
    environment:
      - HOST=forestsqldb
      - PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=forestInteractive
      - BASE_URL=http://kr8tif.lawaapp.com:1338
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["nest", "start", "sms-scheduler"]
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
  mysql:
    container_name: forestsqldb
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=forestInteractive
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
