export const PERMISSIONS_METADATA_KEY = 'permissions',
	BEARER = 'Bearer',
	ENTITY_NAMES = {
		PERMISSION: 'permission',
		ROLE: 'role',
		ROLE_PERMISSIONS: 'role_permissions',
		ACCESS_TOKEN: 'access_token',
		USER_ROLES: 'user_roles',
		USER: 'user',
		VERSION: 'version',
		RECIPIENTS: 'recipients',
		SENT_SMS: 'sent-sms',
		SCHEDULER: 'scheduler',
	},
	FORGOT_PASSWORD_EMAIL_TITLE = 'Forgot Password',
	APP_NAME = 'App Name',
	APP_NAME_EMAIL = 'Team App Name',
	MARKETING_CONSENT = 'subscribed';
